spring:
  config:
    import: file:${user.home}/.latte/worker.yml

  cloud:
    config:
      import-check:
        enabled: false

management:
  endpoints:
    web:
      exposure:
        include: refresh

server:
  port: 8081