spring:
  profiles:
    active: prod

  datasource:
    url: jdbc:h2:~/.latte/records;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: update

  config:
    import: file:${user.home}/.latte/controller.yml

  cloud:
    config:
      import-check:
        enabled: false

management:
  endpoints:
    web:
      exposure:
        include: refresh

---
spring.config.activate.on-profile: dev

latte:
  home.path: ${user.home}/.latte
  scripts:
    path: git-data/latte_repo
    auth-file: git-data/.htpasswd
  logs.path: ${user.home}/.latte/log

---
spring.config.activate.on-profile: prod

latte:
  home.path: ${user.home}/.latte
  scripts:
    path: /var/www/git/latte_repo
    auth-file: /var/www/git/.htpasswd
  logs.path: ${user.home}/.latte/log
