version: '3.7'
services:
  controller-gui:
    build:
      context: ../controller/gui
      dockerfile: controller/gui/Dockerfile

  controller-api:
    build:
      context: ../controller/api
      dockerfile: ../../docker/controller/api/Dockerfile

  controller-git:
    build:
      context: ../controller/git-server
      dockerfile: ../../docker/controller/git-server/Dockerfile

  worker:
    build:
      context: ../worker/api
      dockerfile: ../../docker/worker/Dockerfile