version: '3.7'
services:
  controller-gui:
    image: yunjae2/latte-controller-gui:1.2.0
    container_name: latte-controller-gui
    environment:
      - PORT=80
      - API_URI=http://controller-api:8080
    ports:
      - "80:80"
    profiles:
      - "controller"
    depends_on:
      - controller-api

  controller-api:
    image: yunjae2/latte-controller-api:1.2.0
    container_name: latte-controller-api
    volumes:
      - type: volume
        source: gitdata
        target: /var/www/git
      - type: volume
        source: rundata
        target: /root/.latte
    ports:
      - "8080:8080"
    profiles:
      - "controller"
    depends_on:
      - controller-git

  controller-git:
    image: yunjae2/latte-controller-git:1.2.0
    container_name: latte-controller-git
    volumes:
      - type: volume
        source: gitdata
        target: /var/www/git
    ports:
      - "8082:80"
    profiles:
      - "controller"

  worker:
    image: yunjae2/latte-worker:1.2.0
    container_name: latte-worker
    ports:
      - "8081:8081"
    profiles:
      - "worker"

volumes:
  gitdata:
    name: latte-gitdata
  rundata:
    name: latte-rundata