version: '3.7'
services:
  controller-frontend:
    build:
      context: ../controller/frontend
      dockerfile: ../../docker/controller/frontend/Dockerfile

  controller-backend:
    build:
      context: ../controller/backend
      dockerfile: ../../docker/controller/backend/Dockerfile

  controller-git:
    build:
      context: ../controller/git-server
      dockerfile: ../../docker/controller/git-server/Dockerfile

  worker:
    build:
      context: ../worker/api
      dockerfile: ../../docker/worker/Dockerfile