version: '3.7'
services:
  controller-frontend:
    build:
      context: ../controller/frontend
      dockerfile: ../../docker/controller/frontend/Dockerfile
    image: yunjae2/latte-controller-gui:0.1.1
    environment:
      - PORT=80
      - BACKEND_URI=http://controller-backend:8080
    ports:
      - "3001:80"
    profiles:
      - "controller"
    depends_on:
      - controller-backend

  controller-backend:
    build:
      context: ../controller/backend
      dockerfile: ../../docker/controller/backend/Dockerfile
    image: yunjae2/latte-controller-api:0.1.1
    volumes:
      - type: volume
        source: gitdata
        target: /var/www/git
    ports:
      - "8080:8080"
    profiles:
      - "controller"
    depends_on:
      - controller-git

  controller-git:
    build:
      context: ../controller/git-server
      dockerfile: ../../docker/controller/git-server/Dockerfile
    image: yunjae2/latte-controller-git:0.1.1
    volumes:
      - type: volume
        source: gitdata
        target: /var/www/git
    ports:
      - "8082:80"
    profiles:
      - "controller"

  worker:
    build:
      context: ../worker/api
      dockerfile: ../../docker/worker/Dockerfile
    image: yunjae2/latte-worker:0.1.1
    ports:
      - "8081:8081"
    profiles:
      - "worker"

volumes:
  gitdata: