version: '3.7'
services:
  controller-backend:
    build:
      context: ../controller/backend
      dockerfile: ../../docker/controller/backend/Dockerfile
    image: yunjae2/latte-controller-api:0.1.1
    ports:
      - "8080:8080"
    profiles:
      - "controller"

  controller-git:
    build:
      context: ../controller/git-server
      dockerfile: ../../docker/controller/git-server/Dockerfile
    image: yunjae2/latte-controller-git:0.1.1
    ports:
      - "8082:80"
    profiles:
      - "controller"

  worker:
    build:
      context: ../worker/api
      dockerfile: ../../docker/worker/Dockerfile
    image: yunjae2/latte-worker:0.1.1
    ports:
      - "8081:8081"
    profiles:
      - "worker"