spring:
  datasource:
    url: jdbc:h2:~/.latte/records
    driver-class-name: org.h2.Driver
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: update

  config:
    import: file:${user.home}/.latte/controller.yml