spring:
  datasource:
    url: jdbc:h2:~/.latte/records;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: update

  config:
    import: file:${user.home}/.latte/controller.yml

  cloud:
    config:
      import-check:
        enabled: false

management:
  endpoints:
    web:
      exposure:
        include: refresh